[project]
name = "accord"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Terry Brooks Jr", email = "Terry.Arthur@BrooksJr.com" }
]
requires-python = ">=3.12"
dependencies = [
    "sqlmodel>=0.0.48",
]

[project.scripts]
accord = "accord:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
