apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: $CLICKHOUSE_USER
      defaultDatabase: $CLICKHOUSE_DB
    secureJsonData:
      password: $CLICKHOUSE_PASSWORD

  - name: PostgreSQL
    uid: postgres
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: $POSTGRES_USER
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1700
    secureJsonData:
      password: $POSTGRES_PASSWORD
